version: "3.7"
services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    container_name: TechApp
    working_dir: /var/www
    volumes:
      - ../src:/var/www


  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d

